name: Frontend CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Verify HTML, CSS, JS Files
      run: |
        ls
        echo "Frontend project checked successfully"